### ISSUE TITLE
Regular Webhook ESOCKETTIMEOUT errors

### ISSUE THREAD

**Issue by ikendall** [spark/cloud#29]
### Observed behavior
Persistent ESOCKETTIMEOUT errors in response to Webhook - caused by timeout period of 5secs. Likely cause is AWS is slower to respond than this (using Lambda).  My Lambda function has to complete a number of other HTTP requests before being able to return to Webhook, which are taking longer than 5 secs.

## Feature Requests
Extend the 5 secs before triggering ESOCKETTIMEOUT error to long time ... or make it configurable by the user in order to be able to match to Webhook behavior.

**Comment by mguntli** [comment]
Webhook timeouts should be **increased to 20 seconds** since the 27th february 2018:

https://community.particle.io/t/reliability-analysis-from-electron-particle-cloud-azure-iot-hub/39253/22
> Our team has now deployed an increase in the webhook timeouts to 20 seconds across the board.
> Please let us know if you see a decrease in the error rate/sleeping webhooks after this change.

Particle team - please update the reference page of webhooks with the extended timeout:
https://docs.particle.io/reference/webhooks/#error-limits

**Comment by CullenShane** [comment]
As @mguntli mentioned, we've updated all webhooks to have a 20 second timeout.  With the exception of Azure IoT Hub which has a 60 second timeout.

We've observed a marked decrease in reported timeout errors since increasing the timeout.
