### ISSUE TITLE
CLI 1.34.0 + System Firmware 0.7.0 - Can't connect to unsecured network

### ISSUE THREAD

**Issue by wilcoxmd** [spark/cloud#52]
I'm unable to get my P1 to connect to an unsecured Wi-Fi network when using the CLI. I am running system firmware version 0.7.0 and CLI version 1.34.0

### Expected behavior
When using `particle serial wifi`, I expect it to be able to auto-detect the Wi-Fi security (or allow me to enter it manually) and then automatically connect if the security type is unsecured.

### Observed behavior
After auto-detecting the Wi-Fi security type as unsecured, I receive a serial timeout error that reads:
`Something went wrong: Serial timed out`
`Error configuring Wi-Fi: Serial timed out`

When I then manually put in that the network is unsecured, I receive a different error message: 
`Error in particle-cli:`
`opts.security.indexOf is not a function`

In both cases, I am unable to connect to the unsecured Wi-Fi network. 

### Steps to reproduce
1. Use system firmware 0.7.0 running on a P1, and CLI version 1.34.0. 
2. Try to connect to an unsecured Wi-Fi network.

Also of note, I was able to get around the issue and connect to the network by downgrading my system firmware back to 0.6.3.

**Comment by monkbroc** [comment]
I am not able to reproduce this using the (Sparkfun P1 Redboard)[https://www.sparkfun.com/products/13321]

Sometimes this type of error is because your application is using the USB serial port for communication and the listening mode parser is not able to use the serial port for communication at the same time.

Can you reproduce while running in safe mode (hold reset and mode/setup, release reset and holde mode/setup until the LED blinks magenta)?

You can also connect directly to the serial port using a program like `screen /dev/ttyACM*` (Linux) or `screen /dev/tty.usbmodem*` (Mac) or using PuTTY to the correct COM port (Windows)

**Comment by wilcoxmd** [comment]
@monkbroc, I did revisit this and was unable to reproduce as well. Not sure what the issue was before... perhaps I was indeed using the USB port for something else at the time without realizing it. I was also on a network that I no longer have access to, so I can't retest in that specific situation. I've gone ahead and closed this issue.
